version: "3.9"

services:

  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: puissance4_server
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  player1_vm2:
    build:
      context: ../player
      dockerfile: Dockerfile
    container_name: puissance4_player1_vm2
    depends_on:
      - server
    environment:
      - PLAYER_NAME=player1_vm2
      - SERVER_HOST=server
      - SERVER_PORT=5000
    restart: unless-stopped

  player2_vm2:
    build:
      context: ../player
      dockerfile: Dockerfile
    container_name: puissance4_player2_vm2
    depends_on:
      - server
    environment:
      - PLAYER_NAME=player2_vm2
      - SERVER_HOST=server
      - SERVER_PORT=5000
    restart: unless-stopped
